### ISSUE TITLE
iOS 14: Siri Accessibility Settings?

### ISSUE THREAD

**Issue by Stickyhavr** [FifiTheBulldog/ios-settings-urls#1]
Hello, hope it's ok to post here.

I would love to find an easy way to toggle "Type to Siri" on and off without having to navigate the menus. I figured the easiest way might be to use Shortcuts to open the url but I can't seem to find the right subpath.

I've tried prefs:root=ACCESSIBILITY&path=SIRI (and several case variations like Siri or siri) but it doesn't seem to be any of those. Any ideas on other things to try? I'm in iOS 14.0.1 at the moment. Thanks!

**Comment by FifiTheBulldog** [comment]
I tried the same URLs, and I couldn't find it either. It's probably something ridiculously obscure.

Nonetheless, here are a few combinations of words that you could try (I haven't actually tried most of them myself):

- Siri settings
- Siri accessibility
- Accessibility Siri
- Siri general
- General Siri
- Type to Siri
- Siri Input
- Siri Feedback
- Siri Voice Feedback

**Comment by Stickyhavr** [comment]
Thanks for your reply. I just tried a bunch of those but couldn't find it. When I have time later I'll try again and keep a list of what I've tried so that others don't need to do the same work again. And, of course, if I find it I'll post it here so you can add it to the list.  Thanks.

**Comment by FifiTheBulldog** [comment]
With the recent and massive contribution from u/ZJ_Adran on Reddit (and my subsequent commits), the correct URL for Accessibility → Siri is now in the list:

`prefs:root=ACCESSIBILITY&path=SIRI_SETTINGS_TITLE`

I never would have guessed that one; it was dumped from system files.

**Comment by Stickyhavr** [comment]
Got an email with the new post. Thanks!!! It works great.
