### ISSUE TITLE
URL to iCloud Hide My Email

### ISSUE THREAD

**Issue by ghost** [FifiTheBulldog/ios-settings-urls#12]
I access this menu so frequently so I'd love to make a shortcut to it. I've spent the last half hour trying to find the URL to it, but no luck so far.

**Comment by oguinjr** [comment]
This is why I’ve come here. This url will get you pretty close. 
prefs:root=APPLE_ACCOUNT&path=ICLOUD_SERVICE

**Comment by ptufts** [comment]
opened a PR to add the shortcut and resolve this issue.

https://github.com/FifiTheBulldog/ios-settings-urls/pull/31

**Comment by FifiTheBulldog** [comment]
Thanks for this! PR merged.
