### ISSUE TITLE
URL to iCloud Private Relay

### ISSUE THREAD

**Issue by n1msk** [FifiTheBulldog/ios-settings-urls#13]
If #12 can be found, then this can too I'd assume.

**Comment by n1msk** [comment]
Not a perfect solution, but makes accessing this menu quite a bit easier.

https://github.com/FifiTheBulldog/ios-settings-urls/issues/12#issuecomment-918744538

**Comment by FifiTheBulldog** [comment]
I'll leave this and #12 open for now. If I find direct URLs for these pages (or someone else does), then I'll add them.

**Comment by OMGnotThatGuy** [comment]
URL for Private Relay -> prefs:root=APPLE_ACCOUNT&path=ICLOUD_SERVICE/INTERNET_PRIVACY

Or download existing shortcut from here -> https://www.reddit.com/r/shortcuts/comments/ptomdv/shortcut_to_get_to_the_private_relay_beta/
