### ISSUE TITLE
URL to open workday Ios app from my app

### ISSUE THREAD

**Issue by vneethareddy** [FifiTheBulldog/ios-settings-urls#14]
I tired with different schemes. nothing worked. need help to launch workday app from my app.
i tried with workday:// and workdayapp:// and  com.workday.workdayapp.
nothing worked. thanks in advance,

**Comment by FifiTheBulldog** [comment]
Hi there. Unfortunately, apps' own URL schemes are outside the scope of this repository. This only covers the URLs for the Settings app, not iOS URL schemes in general.

This article (originally on GadgetHacks but now only available elsewhere) includes the Workday URL scheme: https://adrets.net/always-updated-list-of-ios-app-url-scheme-names-paths-for-shortcuts-ios-iphone-gadget-hacks/

**Comment by alreadythere** [comment]
> I tired with different schemes. nothing worked. need help to launch workday app from my app. i tried with workday:// and workdayapp:// and  com.workday.workdayapp. nothing worked. thanks in advance,

did you figure out how to launch workday from a URL?

**Comment by alreadythere** [comment]
> I tired with different schemes. nothing worked. need help to launch workday app from my app. i tried with workday:// and workdayapp:// and  com.workday.workdayapp. nothing worked. thanks in advance,

I found it, it's "workday+https://"

https://medium.com/@contact.jmeyers/complete-list-of-ios-url-schemes-for-third-party-apps-always-updated-5663ef15bdff
