### ISSUE TITLE
Line settings of sim / esim accessible via network operator name

### ISSUE THREAD

**Issue by Chefkeks** [FifiTheBulldog/ios-settings-urls#15]
Hi there,

found a way to access the controls (eg. to disable a line) when using SIM and eSIM:

prefs:root=MOBILE_DATA_SETTINGS_ID&path=Telekom.de

I just set the path variable to the name of the network operator (here: Telekom.de) as Apple shows it as title once you are in the settings there. Possible trap: Upper- and lowercase - so watch out! Eg. telekom.de with lower T at the beginning didn’t work!

Unfortunately both of my sim cards (so the physical nano as well as the esim) are from Telekom.de… so always ending up on the primary (physical) sim and can’t yet get to the second esim. Maybe there is a way to access the second entry for the esim, despite it is also showing Telekom.de as title, but haven’t figured that out yet.

Anyway if you like to add this finding, feel free to do so.

Cheers!
Michael

**Comment by FifiTheBulldog** [comment]
Thank you for this! I'll add it.

**Comment by FifiTheBulldog** [comment]
Added
