### ISSUE TITLE
Cannot get a closer access to cellular switch menu

### ISSUE THREAD

**Issue by zrwang** [FifiTheBulldog/ios-settings-urls#3]
I am using iOS14.3, for the following two urls, I can only get to the level of mobile data settings but the level of cellular data options.

Cellular: prefs:root=MOBILE_DATA_SETTINGS_ID
Cellular → Cellular Data Options: prefs:root=MOBILE_DATA_SETTINGS_ID&path=CELLULAR_DATA_OPTIONS

**Comment by FifiTheBulldog** [comment]
That's weird. I just tried that URL on my iPhone, running iOS 14.3 as well, and it worked perfectly.

**Comment by zrwang** [comment]
Interesting, both URLs can only lead me to the page one level above cellular data selection page. Let me post some pictures here.

The setting for Shortcuts:
![661612749146_ pic](https://user-images.githubusercontent.com/5280342/107167324-956f4980-69f3-11eb-9632-fbba0c6279e9.jpg)

The page I can get to by the URL (prefs:root=MOBILE_DATA_SETTINGS_ID&path=CELLULAR_DATA_OPTIONS):
![641612749100_ pic](https://user-images.githubusercontent.com/5280342/107167392-c0599d80-69f3-11eb-9b4f-d7761347229f.jpg)

The page that I really want to reach by a single click:
![651612749124_ pic](https://user-images.githubusercontent.com/5280342/107167426-d23b4080-69f3-11eb-894d-5a888da1caef.jpg)

**Comment by FifiTheBulldog** [comment]
What if you try MOBILE_DATA_OPTIONS instead of CELLULAR_DATA_OPTIONS for the path? It appears to be the same page, although mine looks a little different since I only have one SIM. CELLULAR_DATA_OPTIONS works for me, but try MOBILE_DATA_OPTIONS since that seems to be the terminology preferred for your region.

**Comment by zrwang** [comment]
Thanks for your answer which served an excellent hint to me. Instead of MOBILE_DATA_OPTIONS, MOBILE_DATA_SETTINGS can lead me to the right page. I think you can add that specific url into your URL Scheme. Hope it can also help others.

**Comment by FifiTheBulldog** [comment]
Awesome! I'll add that to the list.
