### ISSUE TITLE
VPN toggle 

### ISSUE THREAD

**Issue by steve4life8** [FifiTheBulldog/ios-settings-urls#30]
Thanks to you, I can make a shortcut to VPN
prefs:root=General&path=ManagedConfigurationList/VPN

Is there a way to toggle the VPN status? When tap on the shortcut, it should automatically enable the VPN. 

Thanks!
![B4C01F88-EB53-48E0-9ABA-5647EC99C812](https://user-images.githubusercontent.com/41631023/164914138-9f610414-32b0-49e5-b996-2d693c1e60bc.jpeg)

**Comment by FifiTheBulldog** [comment]
These URLs can only bring you to settings, not change them. So what you're looking for would require simulating screen presses, which can't be done in reasonably with Shortcuts or any other app. In short, not possible.

The only method to simulate screen taps involves using the Speak Text action in combination with Voice Control to play voice commands that "tap" the screen. However, this requires your device's microphone to be able to hear its own speakers, and your device's volume must be turned up for that to happen. It's also not particularly reliable, to the point where the extra manual tap to toggle the VPN switch is easier and faster than trying to wait for your phone to do that on its own.

**Comment by steve4life8** [comment]
Thanks, I appreciate your reply

**Comment by bushnerd** [comment]
Thank you, i also tried to find that to control some triggers by url. Now, i am cleared.
