### ISSUE TITLE
Cellular reset statistics button

### ISSUE THREAD

**Issue by JXRIS** [FifiTheBulldog/ios-settings-urls#33]
Please consider adding the URL for `Cellular Reset Statistics button`, I could not find it.

**Comment by FifiTheBulldog** [comment]
I've looked into this, and unfortunately I don't think this will be possible. The cellular data page is controlled by SettingsCellularUI.framework in /System/Library/PrivateFrameworks, and it doesn't seem like there are any provisions in there for the Reset Statistics button to be accessible by an ID or a URL.

**Comment by JXRIS** [comment]
It is possible: `prefs:root=MOBILE_DATA_SETTINGS_ID#Reset%20Statistics`, I did notice that sometimes you have to run this twice before it actually scrolls.

**Comment by FifiTheBulldog** [comment]
Huh, not sure how I didn't find that one. I think I might have only tested it once, which (as you found) didn't scroll to the button until the URL was opened a second time.

I'll add this to the list then. Thanks!
