### ISSUE TITLE
Is it possible to run setting URLs in safari?

### ISSUE THREAD

**Issue by YousufSSyed** [FifiTheBulldog/ios-settings-urls#38]
When I copy and paste one, like `prefs:root=DO_NOT_DISTURB`, into the URL bar, it just makes a Google search instead or running. Could it possibly work if the URL scheme was different?

**Comment by FifiTheBulldog** [comment]
Safari doesn't seem to recognize `prefs:` (no double slash) as a URL scheme, even though it works fine in Shortcuts. However, `prefs` seems to be a restricted URL scheme, so even when I add `//` after the colon, these URLs don't appear to open settings pages properly in Safari or any other app that isn't Shortcuts.

**Comment by YousufSSyed** [comment]
So there's no way to enter the URLs in Safari, or at least you know of?

**Comment by FifiTheBulldog** [comment]
Correct. For example, if I put `prefs://root=DISPLAY` in the address bar and then select "Open" on the prompt to open in Settings, Safari immediately tells me that the address was invalid. I don't think there's any easy way around that.
