### ISSUE TITLE
Problem retrieving media for 11/07/23

### ISSUE THREAD

**Issue by skimark1** [FifiTheBulldog/ios-settings-urls#57]
I've been trying to retrieve media for several meetings in the future since I will be traveling. I keep getting an error for 11/07/23. I'm attaching screenshot to show you what I get. This has been happening for this date for 3 days now.
<img width="699" alt="Screenshot 2023-10-21 at 2 17 29 PM" src="https://github.com/FifiTheBulldog/ios-settings-urls/assets/128306908/90aa0bac-ebf5-411f-b991-b37fc291d129">

**Comment by colin273** [comment]
What does this have to do with iOS Settings URLs?

**Comment by skimark1** [comment]
I clicked the Report problem link in M3 and it took me to this page. Is M3 still being maintained?

Thanks,
Mark Cillis
***@***.***

**Comment by colin273** [comment]
I've never heard of M3. Are you sure you're on the right GitHub repository.

**Comment by skimark1** [comment]
Sorry, must be a broken link in their app. Please ignore and accept my apology for taking your time.

Thanks,
Mark Cillis
***@***.***
