### ISSUE TITLE
URLs missing for Settings → Apple ID → iCloud → iCloud Mail, and sub-menus

### ISSUE THREAD

**Issue by NSExceptional** [FifiTheBulldog/ios-settings-urls#58]
Specifically I would like a URL for _iCloud Mail Rules_

**Comment by atnbueno** [comment]
I would like it too! but this doesn’t work like that. Finding these URLs is a trial and error process, so the issues in this repo are usually to warn us about an URL not working anymore, or to let us know of some new URL found to work (even if it’s just partially).

**Comment by chrisharper22** [comment]
@NSExceptional use `prefs:root=APPLE_ACCOUNT&path=ICLOUD_SERVICE/com.apple.Dataclass.Mail/SERVER_SIDE_RULES`
