### ISSUE TITLE
Assistive Access

### ISSUE THREAD

**Issue by vegathedev** [FifiTheBulldog/ios-settings-urls#59]
Cannot find URL for Assistive Access.

**Comment by chrisharper22** [comment]
@wolferamite Accessibility → Assistive Access: `prefs:root=ACCESSIBILITY&path=CLARITY_UI_TITLE`

**Comment by wolferamite** [comment]
> @wolferamite Accessibility → Assistive Access: `prefs:root=ACCESSIBILITY&path=CLARITY_UI_TITLE`

Thank you!
