### ISSUE TITLE
Mail rule

### ISSUE THREAD

**Issue by Durrant-David** [FifiTheBulldog/ios-settings-urls#78]
Found this online

prefs:root=APPLE_ACCOUNT&path=ICLOUD_SERVICE/com.apple.Dataclass.Mail/SERVER_SIDE_RULES

iCloud->mail->icloud mail rules

**Comment by ahrendsen** [comment]
Hi @Durrant-David,

Thanks for your contribution! Could you also include what phone model you have and the current operating system? I tested this on my iPhone 16 Pro and verified that it is a current URL that works, but it would be interesting to know if it works on older models. I've added your URL to a pull request, so it should get added to the database soon.

Once you've done that, could you also close this issue?

Thanks again,
Karl

**Comment by Durrant-David** [comment]
I tested it on a 12 pro, but have since moved up to 15 pro with no issues.

**Comment by Durrant-David** [comment]
Don't remember what iOS I originally tested it on, but I currently have 18.1
